name: publish
on: [push]
jobs:
publish-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: colepatters
password: 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
run: |
       docker build . --tag ghcr.io/colepatters/colepattersonhomelab.net:latest
       docker run ghcr.io/colepatters/colepattersonhomelab.net:latest
       docker push ghcr.io/colepatters/colepattersonhomelab.net:latest
